### PR TITLE
Feature/about screen

### PR DESCRIPTION
**Pull request by isdampe**
This PR adds a new "about" screen with some retro-style animations. Some basic information about the Arcade Machine is hard-coded into the files but can be easily edited.

Also displayed is statistics regarding the project, including source code line count, # git commits, # git branches, # contributors, and the actual contributor list and their commit number. These are read from files in a `stats/` directory. The stats in these files are generated automatically by `.scripts/generate-stats.sh`, which has been configured to executed with each build using when using `make` - so they should always be pretty much up to date.

I've currently hooked up the screen to play immediately after the intro splash screens (exit by pressing escape). This can obviously be changed to the suitable place. 

Screen Shot 2022-09-08 at 8 35 05 pm

### CODE REVIEW

**Comment by studioant** [comment]
This is excellent! Nice work Richard. I think this is best served in the options menu when stats button is pressed. Perhaps we merge refactor/options and then integrate this. Top notch!

**Comment by Delcari** [comment]
I love that the stats dynamically update that's awesome 🥹

**Review by Delcari — CHANGES_REQUESTED** [review]
I'm currently experiencing issues loading the font & music, not sure whether they need to be referenced in the bundle file or not. Excluding this, animations perform as expected nice work :medal_military: 
Screenshot_2022-09-11_22-54-58

**Comment by isdampe** [comment]
Thanks @Delcari - [6606c45](https://github.com/thoth-tech/arcade-machine/pull/69/commits/6606c45a4b2d54cc34644f0d88bdf04bd017a122) refactors to use the resources bundle. Could you test this now? If the music doesn't work, I'll convert the `.ogg` to `.mp3` like the others.

**Comment by lachfoy** [comment]
The music is a jam! 🕺
Technically all works perfectly on Ubuntu 20.04(WSL2).
From a design/accessibility perspective the movement and high contrast could be a bit distracting but that's the only thing I could criticize. Really great job!

**Review by Delcari — APPROVED** [review]
https://github.com/thoth-tech/arcade-machine/pull/69/commits/6606c45a4b2d54cc34644f0d88bdf04bd017a122 Seems to have resolved the issue, well done!
Works as expected on Windows, Ubuntu w/ WSL and Manjaro

**Review by studioant — CHANGES_REQUESTED** [review]
Great work Richard, only request from me is to move this from the intro sequence to become a selection of the Options menu.

**Comment by isdampe** [comment]
@studioant the latest changes refactor this to open upon selecting the "stats" item in the options menu. Are you able to test / confirm we are good to merge?

**Review by studioant — APPROVED** [review]
Nice work @isdampe!
One issue being experienced on Windows is the `find` call in `generate-stats.sh`

image

I'm assuming this is not an issue on Linux? (Something to do with the period syntax? I tried escaping it to no avail)

I still think this should be merged, so that it is present in the release; a fix for Windows can be developed later.

**Comment by studioant** [comment]
Have committed a fix for it, @isdampe can you confirm this behaves ok on Linux?

**Comment by isdampe** [comment]
Sorry for the late response - can confirm it works on Linux @studioant

**Pull request merged**
