### PR TITLE
Refactor: Remove global Include.h dependency

### PR DESCRIPTION
**Pull request by isdampe**
This PR refactors all `*.h` files to remove the order-specific dependency on `Includes.h`. This has only been tested on macOS and Linux and will probably require some Windows-specific tweaking.

What has been performed:

1. All header files have had include guards [1] added to them to prevent duplicate inclusions and dependency resolution issues
2. Each header file now specifically includes what is required for code execution
3. `Includes.h` has been removed

[1] https://en.wikipedia.org/wiki/Include_guard

### CODE REVIEW

**Comment by lachfoy** [comment]
Hey, so the calls to windows functions are a bit broken, but as a quick fix I've pushed a new change which allows us to ignore the windows functions in menu.h with `#define USE_WINAPI_FUNCTIONS` setting this to 0 or 1 will enable or disable the winapi calls. I've also replaced calls to `Sleep` with SplashKit's `delay`.
Compiling now works on Windows, if we ignore the winapi calls for now.

**Comment by isdampe** [comment]
Got it. I think if we add conditional including for `window.h` on any file that uses `win32` API calls, it should resolve as expected. Is this something you're able to tackle @lachfoy?

E.g. 

```c++
#ifdef _WIN32
#include <windows.h>
#endif
```

**Comment by lachfoy** [comment]
> Got it. I think if we add conditional including for `windows.h` on any file that uses `win32` API calls, it should resolve as expected. Is this something you're able to tackle @lachfoy?
> 
> E.g.
> 
> ```c++
> #ifdef _WIN32
> #include <windows.h>
> #endif
> ```

Done 😄

**Review by Delcari — APPROVED** [review]
Compiles and runs as expected
Windows: ✅
Ubuntu w/ WSL: ✅
Wonderful change, great that you added include guards as well, nice work 👍

**Pull request merged**
