### PR TITLE
Refactor/seperate h cpp files

### PR DESCRIPTION
**Pull request by lachfoy**
refactor: definitions moved Splashscreen.h -> Splashscreen.cpp
refactor: definitions moved MenuButton.h -> MenuButton.cpp
refactor: definitions moved GameScreenButton.h -> GameScreenButton.cpp
refactor: definitions moved ArcadeMachine.h -> ArcadeMachine.cpp
refactor: definitions moved Button.h -> Button.cpp
refactor: definitions moved ConfigData.h -> ConfigData.cpp
refactor: definitions moved GridLayout.h -> GridLayout.cpp
refactor: definitions moved Menu.h -> Menu.cpp
refactor: definitions moved Option.h -> Option.cpp
refactor: definitions moved Tip.h -> Tip.cpp
refactor: definitions moved Selector.h -> Selector.cpp

refactor: renamed class Grid -> GridLayout
refactor: cleaned up formatting in Option.h
refactor: "std::" added to string/vector in Database.h

fix: free memory in ArcadeMachine destructor
fix: free memory in Menu class destructor
fix: free memory (m_tables) in Database class destructor
fix: add destructor definition to Table
fix: add destructor definition to Tip

issue: Menu relies on constants defined in ArcadeMachine.h (circular dependency)

issues:
Button class has a lot of getters/setters but it is a completely public class
Some unused functions

GridLayout ownership of pointers is not clear

### CODE REVIEW

**Comment by isdampe** [comment]
Looking good. Compiling fails on macOS with inclusion path errors like examples below [1].

Suggest moving `includes` inside `src/` and then updating include paths to `#include "includes/[header.h]"`. I will make some changes and push them into this branch

[1] 
```
1 error generated.
src/program.cpp:1:10: fatal error: 'ArcadeMachine.h' file not found
#include "ArcadeMachine.h"
```

**Comment by studioant** [comment]
This is good Lachlan! Tested and compiled on Windows. Unfortunately there is no speedup in compile time as I had expected. 

We do need to update the compile command to include the .cpp dir and all files like so:
`skm clang++ src/*.cpp -o test -lstdc++fs -Iinclude`

Re: Button class getters/setters,. this is true, but I don't believe it's an issue, and I don't believe it should change since the method of using getters and setters to access members is good practice.

**Comment by isdampe** [comment]
@studioant compile speed up can be introduced using a `Makefile` with this new architecture (and compiling will become as easy as running `make`). I'll send up some commits to this branch for testing this

**Comment by isdampe** [comment]
@studioant @lachfoy the last four commits adds a primitive make file that will speed up builds using incremental objects. I've only tested on macOS and may need tweaks to run on Linux / Windows but feel free to check it out.

Measurements:

```
Clean build (first time)
Makefile: 3.37s user 0.31s system 97% cpu 3.766 total
Manual: 3.32s user 0.20s system 99% cpu 3.518 total
==
Result: Manual is faster
==

Build with changes (clean build has happened once or more, one source file was modified)
Makefile: 0.23s user 0.05s system 93% cpu 0.299 total
Manual: 3.33s user 0.20s system 99% cpu 3.542 total
==
Result: Makefile is faster
==
```

**Comment by lachfoy** [comment]
> Unfortunately there is no speedup in compile time as I had expected.
@studioant  Yeah absolutely I had hoped just seperating out the files would lead to a dramatic increase in compile time. Unfortunately I have no idea how skm works and I don't think it's particularly well optimized, so I did not see any improvement either.

Ultimately I've realised - as I've started to read through the code more throuroughly - I think large refactors may actually be a detriment to any working efficiency. Everything is so tightly coupled that if our goal was to have an easily readable and extensible codebase, it would be *much* easier to build an "Arcade Machine 2" application from scratch.
Of course I **don't** think this is worth the time, as we already have a mostly finished application. As such, I think that shifting focus to a MVP is a better idea than dealing with refactoring. As a result, I would be more open to making changes that could help the efficiency of @Delcari , @zbrydon , @isdampe  instead of making destructive refactor changes.
Would love to hear thoughts

I'll bring this to the next meeting and make sure this branch is NOT merged until then. If it's less destructive, I could roll back the file seperation changes of this branch and just keep the memory fixes.

**Comment by isdampe** [comment]
@lachfoy @studioant I really think this should still be merged. Tightly coupled or not, this is a huge improvement on readability for new contributors coming to the code base. You can now fairly easily find anything you want to work on (which was difficult for someone unfamiliar with the code base before). @lachfoy don't underestimate the improvement you have made here or the improvement in long term maintainability of the project.

Patch [47fb2b0](https://github.com/thoth-tech/arcade-machine/pull/58/commits/47fb2b05bb1e53b29cd9a6ad2bea9fda79345796) dramatically increases build times by compiling each `.cpp` to a shared object and linking them all together. Compiling using this method will mean only the `.cpp` files that have changed need to be re-compiled. You should try it out - it is much faster. This is only possible because of this refactoring work you have done.

**Comment by studioant** [comment]
@lachfoy @isdampe Tested using `make`, results achieve the speedup we were expecting, great work Richard!

I agree with @isdampe, these changes are now a great improvement to the speed of compilation and the general overall readability of the codebase. Happy to merge this today if everyone else is happy.

**Comment by lachfoy** [comment]
@isdampe huge props for working out the Makefile -- it works really well.
I have however rolled back the include directory change since most open source C++ projects follow this directory structure. I added `-Iinclude` to the makefile but I'm not sure if I've done it correctly, review would be appreciated.

Otherwise everything works and I would be happy to merge 👍

**Comment by isdampe** [comment]
No problem @lachfoy, I'll test the Makefile then we are good to merge

Again, well done!

**Comment by isdampe** [comment]
Looks good. Just added an `INCDIRS` declaration in case it ever needs to change or the build gets complicated.

**Review by isdampe — APPROVED** [review]
Tested and working on macOS and Debian Linux.

**Comment by isdampe** [comment]
@lachfoy if you've tested on Windows (`make clean` and then `make`) and it works - go ahead and press the merge button ;)

**Pull request merged**
