### PR TITLE
Grid layout

### PR DESCRIPTION
**Pull request by Delcari**
## Added support for different classes
+ Sprite and Button support
+ New function which displays the boundaries of the cells DrawCells()

**NOTE:** Please review method used to handle and draw buttons, additionally I'm unsure of way to clear the button variable when the cell is overwritten.

### CODE REVIEW

**Comment by studioant** [comment]
@Delcari Tested main menu design using grid. Working great. One addition suggestion to make drawing backgrounds easier, an option to draw bitmap as normal (top left to [0,0] ) instead of permanent centering, for full screen drawing.

image

**Review by sarahgos — APPROVED** [review]
Just tried this out with the button class and it works beautifully, looking forward to integrating this with the Selector class, well done Riley!

**Comment by studioant** [comment]
@Delcari It does throw a compilation error because enum values are already taken (I think SplashKit already uses BITMAP and SPRITE, i changed them to BMP, BTN, SPT)
Otherwise, great job! Create a real PR and ready to merge i reckon

MicrosoftTeams-image

**Comment by Delcari** [comment]
## Quick Additions

Now able to:  
+ Set the background
+ Toggle centering of cell items
+ Get a cell from the grid

Fixed:  
+ Name collision with other enumeration

**Pull request merged**
