### PR TITLE
macOS & Linux game execution support - Feature/spawn process

### PR DESCRIPTION
**Pull request by isdampe**
This PR adds supports for spawning game processes on both macOS and Linux.

This currently won't work on macOS and Linux without manually overriding `filePath` in `Menu::startGame` to point to a real executable, since the games `git` repository only has Windows binaries.

We need to look at updating the games repository to either include the source code of games (and compile them as they are run the first time) or include pre-compiled binaries for both macOS and Linux.

### CODE REVIEW

**Comment by lachfoy** [comment]
I think we should look into compiling the games as they are run for the first time, but for now we should include precompiled binaries. I'll look into including those in arcade-games repo, then give it a test 👍

**Comment by studioant** [comment]
PR #63 addresses fetching the Linux and MacOS paths to binaries to compliment this PR

**Comment by isdampe** [comment]
Latest round of commits tidies up spawn on macOS and Linux. Once the games are compiled using the automatic compilation events, and a convention on the automatic builds is set - we can tidy up `ConfigData::getExecutablePath()` to support auto-detecting the pre-built binaries for execution (with the current code as a fallback).

**Comment by isdampe** [comment]
@Delcari @zbrydon @studioant the latest commits in this branch now execute games in the current manner

1 - Check to see if a binary file exists in `gamePath/[current-operating-system]-[current-instruction-set][file-extension]`
2 - If it does, execute this
3 - If it does not, fall back to the binary file behaviour as manually specified in the `config.txt` file.

This will require an update on the `arcade-games` repository. I've did create a branch updated the `compile-games.yml` script but am getting 

```
To https://github.com/thoth-tech/arcade-games.git
 ! [remote rejected] refactor/auto-compilation-naming -> refactor/auto-compilation-naming (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/compile-games.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/thoth-tech/arcade-games.git'
```

back from GitHub.

The change we need is just the convention of naming the binary file - which should match

```
[gamePath]/builds/[os]-[instruction-set][extension?]
```

For example with sktetris, this would be

Windows - `sktetris/builds/windows-x86.exe`
Linux (x86) - `sktetris/builds/linux-x86`
Linux (ARM) - `sktetris/builds/linux-arm`

and if we add macOS support, `sktetris/builds/macos-x86`.

If we can update and get all games compiled, I believe this should start working on Linux with little to no further adjustments.

**Review by studioant — APPROVED** [review]
Legendary!

**Pull request merged**
