### PR TITLE
Refactor/static resources folder

### PR DESCRIPTION
**Pull request by isdampe**
This PR moves all resources into a specified "resources" directory and requests splashkit use this directory for bundle loading.

This PR is dependent on #35 and #37

### CODE REVIEW

**Review by Delcari — CHANGES_REQUESTED** [review]
Checked out to your branch refactor/static-resources-folder. Tried compiling and running the application on Windows, from MSYS and encountered some strange issues 👽. 
I'll look into it over the next day or two, but if anyone has any solutions let me know.
image

**Review by studioant — CHANGES_REQUESTED** [review]
Assets are not being referenced correctly, breaking drawing functions

image

**Comment by isdampe** [comment]
Thanks for testing. I don't (currently) have access to a Windows environment for testing. I'll get a virtual machine set up for testing a fix.

**Comment by isdampe** [comment]
Suspect issues with mixing path separators over Linux/macOS and Windows. `splashkit-core` internally differentiates these [1]. Will try applying similar logic.

[1] https://github.com/splashkit/splashkit-core/blob/9d52e752d1ea9d1b80a618794611661aa54afd1e/coresdk/src/backend/utility_functions.cpp#L117

**Pull request closed without merging**
