### PR TITLE
Connected games menu with button class and grid class. 

### PR DESCRIPTION
**Pull request by sarahgos**
Added a third constructor in button class to handle games buttons. Added highlight layer to games in menu. I did have an issue with these two lines in GridLayout with the game buttons, I was unsure of how to rectify this, so locally I have commented them out in order for the games menu to display.
gridclass

### CODE REVIEW

**Comment by Delcari** [comment]
> 

Ah my apologies, I assumed centre_x and centre _y would be defined upon initialisation of all the buttons as the centre of the bitmap/sprite. Should we address by modifying the button class or grid layout class?

**Comment by studioant** [comment]
@Delcari @sarahgos I have added the centre_x and centre_y to the second button class constructor, grid layout can access those properties. Will push directly to main as a hot fix

**Review by studioant — APPROVED** [review]
This all looks good to me Sarah, good work!

**Review by Delcari — APPROVED** [review]
Looks good 🥇

**Pull request merged**
