### PR TITLE
refactor/options

### PR DESCRIPTION
**Pull request by studioant**
### Merging as a Working Work-in-Progress

This PR contains a refactor of the Options menu. 

The purpose of my refactor is two-fold:
1. To enforce the utilization of our custom classes (`GridLayout`, `Button`, `ButtonNode`, `Selector`) within the Options menu, creating uniformity of coding practice and methodology across the entire program.
2. To tidy the Options menu design by conforming to the already implemented UI design standards, readying the UI/UX for the Alpha release of ArcadeMachine software.

There is still a lot more work to do, but this lays the correct foundation for future development, and a blank canvas for those interested in implementing some bespoke functionality.

A new Button class has been created `OptionsScreenButton` to handle buttons within the Options menu and with it new Button.Enum fields.

Work to be done may include, but is not limited to:
- Music selection functionality
- Music volume functionality
- In depth statistics analysis
- Display selection functionality
- Any other relevant options

These tasks will be raised in Trello and earmarked for future development.

### CODE REVIEW

**Comment by isdampe** [comment]
Tested on macOS and Linux. I am intermittently getting a crash with segmentation fault on both systems when selection "options" in main menu and pressing the enter key. Oddly, it doesn't seem to happen when I click the options button with the mouse.

Terminal output right before crash:
```
Options
zsh: segmentation fault  ./ArcadeMachine
```

**Comment by studioant** [comment]
> Tested on macOS and Linux. I am intermittently getting a crash with segmentation fault on both systems when selecting "options" in main menu and pressing the enter key. Oddly, it doesn't seem to happen when I click the options button with the mouse.
> 
> Terminal output right before crash:
> 
> ```
> Options
> zsh: segmentation fault  ./ArcadeMachine
> ```
> 
> I had to rename one of the resource files to keep SplashKit from emitting warnings too ([e6265a8](https://github.com/thoth-tech/arcade-machine/commit/e6265a85c652597d3425431dfefc7cbd36b75966))
> 
> Otherwise, screen looks like a big improvement.

Conducted persistent testing on Windows and Linux and cannot replicate this seg fault at all. Does anyone else have a Mac env they can test this on to try and replicate the fault @isdampe is experiencing?

**Comment by isdampe** [comment]
@studioant I'll run this through Valgrind and see if a stack trace can identify the cause

**Comment by isdampe** [comment]
That was tough to track down...

lldb yielded
```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x6e6f6614)
    frame #0: 0x00000001095dda43 libSplashKit.dylib`splashkit_lib::sprite_set_x(splashkit_lib::_sprite_data*, float) + 35
libSplashKit.dylib`splashkit_lib::sprite_set_x:
->  0x1095dda43 <+35>: cmpl   $0x53505254, (%rax)       ; imm = 0x53505254
    0x1095dda49 <+41>: je     0x1095ddb0a               ; <+234>
    0x1095dda4f <+47>: movq   %rsp, %rax
    0x1095dda52 <+50>: movl   $0x0, (%rax)
```

meaning a hanging pointer reference a sprite somewhere.

Tracking down through the code, `Option.h` declares 

```c++
Selector m_selectorOptionsMenu;
```

at line 29 which calls the constructor `Selector::Selector`.

`Selector::Selector` sets `m_cursorSprite = create_sprite(bitmap_named("cursor"))`. Since there's no registered bitmap for "cursor" in this execution context, some undefined behaviour happens (and a pointer to somewhere gets set)

Later on, when `Selector::highlightFirst` gets called, `sprite_set_x()` and `sprite_set_y()` get called referencing `m_cursorSprite` (which at this point is undefined behaviour). On my test systems (macOS and Linux), this sometimes causes a segmentation fault.

There's a comment in `Option.cpp` 

>>> // Draw cursor -- no need for cursor in options menu, highlights work well

which explains why there's no `bitmap_named("cursor")` in the context.

To resolve, I have added a property `m_renderCursor = true` to `Selector.cpp`, and specifically flagged as `false` in `Option.h` constructor. Any render calls on `Selector.cpp` regarding the cursor are then conditionally ignored.

@Delcari can you pull my latest commits and confirm they resolve on your system too?

**Comment by studioant** [comment]
Awesome work Richard! Wonder why this only affected non windows env... it really should have been evident everywhere. Great job tracking it down.

**Comment by Delcari** [comment]
Bahahah you beat me to it @isdampe seems about right, I just identified the same issue :laughing: 
image
You're solution seems fine, checking to see if cursor exists before trying to move/draw it, maybe that should variable should be initialized as false within the default constructor.

**Comment by isdampe** [comment]
Agree on defaulting the constructor - anyone want to push up one final commit to tidy it up? I think we're good to merge after that

**Comment by studioant** [comment]
> Agree on defaulting the constructor - anyone want to push up one final commit to tidy it up? I think we're good to merge after that

Sure thing

**Review by isdampe — APPROVED** [review]

**Pull request merged**
