### PR TITLE
Created Menu and Splashscreen classes, connected ConfigData class wit…

### PR DESCRIPTION
**Pull request by sarahgos**
…h menu to display games. Games can be clicked on and opened in a new window. arcade-games repo is clonde/pulled at startup to get most recent games.

### CODE REVIEW

**Comment by DocHolidayHunter** [comment]
Looks good

**Review by DocHolidayHunter — COMMENTED** [review]
Looks good, can clearly see the changes made

**Comment by studioant** [comment]
AWESOME work Sarah! 
Just a few things to consider:
1. tidy up includes files
2. reassess the necessity of 'Game.h'

**Comment by sarahgos** [comment]
Thankyou for the feedback. I will fix these issues and create another draft pull request.

**Pull request closed without merging**
